// ============================================
// Luxury Ops - Mock Hotels Data (14 hotels)
// ============================================

import { Hotel, DestinationBoard } from '@/lib/types';

// === Destination Boards ===
export const destinationBoards: DestinationBoard[] = [
    {
        board_id: 'tokyo-downtown',
        name: '东京都心',
        country: '日本',
        region: '关东',
        description: '繁华都市中的顶级酒店，便捷的交通与购物体验',
        typical_stay_nights: 3,
        best_seasons: ['春季樱花', '秋季'],
        typical_guests: ['商务', '购物', '城市观光'],
        hotel_count: 4,
        advantage_hotel_count: 2,
        price_range_min: 52000,
        price_range_max: 180000,
        avg_advantage_percent: 13,
        display_order: 1,
    },
    {
        board_id: 'kyoto-ancient',
        name: '京都古都',
        country: '日本',
        region: '关西',
        description: '千年古都的传统与现代融合，日式美学的极致体验',
        typical_stay_nights: 3,
        best_seasons: ['春季樱花', '秋季红叶'],
        typical_guests: ['蜜月', '文化体验', '日式控'],
        hotel_count: 4,
        advantage_hotel_count: 2,
        price_range_min: 55000,
        price_range_max: 198000,
        avg_advantage_percent: 18,
        display_order: 2,
    },
    {
        board_id: 'fuji-area',
        name: '富士山周边',
        country: '日本',
        region: '中部',
        description: '富士山绝景与温泉私汤的完美结合',
        typical_stay_nights: 2,
        best_seasons: ['冬季雪景', '秋季'],
        typical_guests: ['蜜月', '温泉', '自然风光'],
        hotel_count: 3,
        advantage_hotel_count: 3,
        price_range_min: 35000,
        price_range_max: 95000,
        avg_advantage_percent: 24,
        display_order: 3,
    },
    {
        board_id: 'hokkaido',
        name: '北海道',
        country: '日本',
        region: '北海道',
        description: '北国温泉秘境，粉雪天堂与自然野趣',
        typical_stay_nights: 3,
        best_seasons: ['冬季滑雪', '夏季避暑', '秋季'],
        typical_guests: ['亲子', '滑雪', '温泉'],
        hotel_count: 3,
        advantage_hotel_count: 2,
        price_range_min: 38000,
        price_range_max: 98000,
        avg_advantage_percent: 22,
        display_order: 4,
    },
];

// === Hotels Data ===
export const hotels: Hotel[] = [
    // ========== 东京都心 (4家) ==========
    {
        hotel_id: 'hoshinoya-tokyo',
        name_cn: '虹夕诺雅 东京',
        name_en: 'Hoshinoya Tokyo',
        name_local: '星のや東京',
        brand: '虹夕诺雅',
        group: '星野集团',
        country: '日本',
        region: '关东',
        city: '东京',
        area_tag: '大手町',
        destination_board: 'tokyo-downtown',
        address_full: '東京都千代田区大手町1-9-1',
        geo_description: '位于东京金融中心大手町，东京站步行5分钟',
        transport_info: '东京站丸之内北口步行5分钟，大手町站直达',
        positioning_short: '都市中的日式旅馆体验',
        positioning_keywords: ['日式旅馆', '温泉大浴场', '都市绿洲', '茶道'],
        target_guests: ['蜜月', '日式控', '深度体验'],
        style_tags: ['日式传统', '现代设计', '城市度假'],
        highlights: ['顶层大浴场可看东京夜景', '每日免费茶道体验', '全套日式待客'],
        price_tier: 'luxury',
        price_range_min: 72000,
        price_range_max: 150000,
        price_range_typical: 82000,
        currency: 'JPY',
        avg_advantage_percent: 24,
        advantage_level: 'good',
        our_primary_channel: 'ikyu_b2b',
        similar_hotels: ['hoshinoya-kyoto', 'aman-tokyo'],
        alternative_hotels: ['peninsula-tokyo'],
        upgrade_options: ['aman-tokyo'],
        budget_options: ['peninsula-tokyo', 'park-hyatt-tokyo'],
        booking_difficulty: 'moderate',
        advance_booking_days: 30,
        peak_seasons: ['樱花季(3月下旬-4月上旬)', '红叶季(11月)'],
        rooms_count: 84,
        opening_year: 2016,
        renovation_year: null,
        checkin_time: '15:00',
        checkout_time: '12:00',
        website: 'https://hoshinoya.com/tokyo/',
        phone: '+81-50-3134-8091',
        email: '',
        notebooklm_url: null,
        official_url: 'https://hoshinoya.com/tokyo/',
        status: '在售',
        info_completeness: 95,
        created_at: '2024-01-01',
        updated_at: '2024-12-01',
        notes_conflicts: null,
    },
    {
        hotel_id: 'peninsula-tokyo',
        name_cn: '东京半岛',
        name_en: 'The Peninsula Tokyo',
        name_local: 'ザ・ペニンシュラ東京',
        brand: '半岛',
        group: '香港上海大酒店',
        country: '日本',
        region: '关东',
        city: '东京',
        area_tag: '日比谷',
        destination_board: 'tokyo-downtown',
        address_full: '東京都千代田区有楽町1-8-1',
        geo_description: '位于银座与皇居之间，尽享都市繁华',
        transport_info: '日比谷站直达，银座站步行3分钟',
        positioning_short: '银座商圈的经典奢华',
        positioning_keywords: ['经典奢华', '购物便利', '服务顶级', '商务'],
        target_guests: ['商务', '购物', '经典奢华控'],
        style_tags: ['经典奢华', '现代商务', '城市中心'],
        highlights: ['俯瞰皇居与银座', '顶级Spa', '便捷购物'],
        price_tier: 'luxury',
        price_range_min: 68000,
        price_range_max: 120000,
        price_range_typical: 75000,
        currency: 'JPY',
        avg_advantage_percent: 9,
        advantage_level: 'none',
        our_primary_channel: 'direct',
        similar_hotels: ['park-hyatt-tokyo', 'mandarin-oriental-tokyo'],
        alternative_hotels: ['hoshinoya-tokyo'],
        upgrade_options: ['aman-tokyo'],
        budget_options: ['park-hyatt-tokyo'],
        booking_difficulty: 'easy',
        advance_booking_days: 14,
        peak_seasons: ['樱花季', '年末年始'],
        rooms_count: 314,
        opening_year: 2007,
        renovation_year: 2022,
        checkin_time: '14:00',
        checkout_time: '12:00',
        website: 'https://www.peninsula.com/tokyo',
        phone: '+81-3-6270-2888',
        email: '',
        notebooklm_url: null,
        official_url: 'https://www.peninsula.com/tokyo',
        status: '在售',
        info_completeness: 90,
        created_at: '2024-01-01',
        updated_at: '2024-12-01',
        notes_conflicts: null,
    },
    {
        hotel_id: 'aman-tokyo',
        name_cn: '安缦东京',
        name_en: 'Aman Tokyo',
        name_local: 'アマン東京',
        brand: '安缦',
        group: 'Aman Resorts',
        country: '日本',
        region: '关东',
        city: '东京',
        area_tag: '大手町',
        destination_board: 'tokyo-downtown',
        address_full: '東京都千代田区大手町1-5-6 大手町タワー',
        geo_description: '大手町塔顶层，俯瞰皇居与东京天际线',
        transport_info: '大手町站直达，东京站步行7分钟',
        positioning_short: '东京天际线上的都市绿洲',
        positioning_keywords: ['极简设计', '都市禅意', '顶级隐私', '安缦'],
        target_guests: ['安缦粉', '设计控', '隐私需求', 'UHNW'],
        style_tags: ['现代极简', '禅意设计', '超奢'],
        highlights: ['33层高空泳池', '安缦标志性服务', '俯瞰皇居'],
        price_tier: 'ultra_luxury',
        price_range_min: 135000,
        price_range_max: 500000,
        price_range_typical: 158000,
        currency: 'JPY',
        avg_advantage_percent: 14,
        advantage_level: 'fair',
        our_primary_channel: 'ikyu_b2b',
        similar_hotels: ['aman-kyoto', 'hoshinoya-tokyo'],
        alternative_hotels: [],
        upgrade_options: [],
        budget_options: ['hoshinoya-tokyo', 'park-hyatt-tokyo'],
        booking_difficulty: 'moderate',
        advance_booking_days: 45,
        peak_seasons: ['樱花季', '年末年始'],
        rooms_count: 84,
        opening_year: 2014,
        renovation_year: null,
        checkin_time: '15:00',
        checkout_time: '12:00',
        website: 'https://www.aman.com/hotels/aman-tokyo',
        phone: '+81-3-5224-3333',
        email: '',
        notebooklm_url: null,
        official_url: 'https://www.aman.com/hotels/aman-tokyo',
        status: '在售',
        info_completeness: 92,
        created_at: '2024-01-01',
        updated_at: '2024-12-01',
        notes_conflicts: null,
    },
    {
        hotel_id: 'park-hyatt-tokyo',
        name_cn: '东京柏悦',
        name_en: 'Park Hyatt Tokyo',
        name_local: 'パークハイアット東京',
        brand: '柏悦',
        group: '凯悦',
        country: '日本',
        region: '关东',
        city: '东京',
        area_tag: '新宿',
        destination_board: 'tokyo-downtown',
        address_full: '東京都新宿区西新宿3-7-1-2',
        geo_description: '新宿摩天楼群中，《迷失东京》取景地',
        transport_info: '新宿站西口步行12分钟，有酒店班车',
        positioning_short: '商务出行的可靠选择',
        positioning_keywords: ['经典商务', '都市景观', '电影取景地', '成熟稳重'],
        target_guests: ['商务', '电影迷', '成熟客群'],
        style_tags: ['经典商务', '都市景观', '成熟稳重'],
        highlights: ['《迷失东京》取景地', 'New York Grill餐厅', '俯瞰新宿夜景'],
        price_tier: 'luxury',
        price_range_min: 52000,
        price_range_max: 95000,
        price_range_typical: 55000,
        currency: 'JPY',
        avg_advantage_percent: 5,
        advantage_level: 'none',
        our_primary_channel: 'direct',
        similar_hotels: ['peninsula-tokyo', 'conrad-tokyo'],
        alternative_hotels: ['hoshinoya-tokyo'],
        upgrade_options: ['aman-tokyo'],
        budget_options: [],
        booking_difficulty: 'easy',
        advance_booking_days: 14,
        peak_seasons: ['樱花季'],
        rooms_count: 177,
        opening_year: 1994,
        renovation_year: 2019,
        checkin_time: '15:00',
        checkout_time: '12:00',
        website: 'https://www.hyatt.com/park-hyatt/tyoph-park-hyatt-tokyo',
        phone: '+81-3-5322-1234',
        email: '',
        notebooklm_url: null,
        official_url: 'https://www.hyatt.com/park-hyatt/tyoph-park-hyatt-tokyo',
        status: '在售',
        info_completeness: 88,
        created_at: '2024-01-01',
        updated_at: '2024-12-01',
        notes_conflicts: null,
    },

    // ========== 京都古都 (4家) ==========
    {
        hotel_id: 'hoshinoya-kyoto',
        name_cn: '虹夕诺雅 京都',
        name_en: 'Hoshinoya Kyoto',
        name_local: '星のや京都',
        brand: '虹夕诺雅',
        group: '星野集团',
        country: '日本',
        region: '关西',
        city: '京都',
        area_tag: '岚山',
        destination_board: 'kyoto-ancient',
        address_full: '京都府京都市西京区嵐山元録山町11-2',
        geo_description: '嵐山大堰川畔，需乘船进入的水边秘境',
        transport_info: '岚山站步行15分钟至船着场，需乘酒店专船5分钟',
        positioning_short: '岚山水边的日式风雅',
        positioning_keywords: ['水边秘境', '日式风雅', '船入住', '岚山'],
        target_guests: ['蜜月', '日式控', '摄影师'],
        style_tags: ['日式传统', '水岸风情', '隐世秘境'],
        highlights: ['乘船入住仪式', '四季庭园景观', '日式早餐体验'],
        price_tier: 'luxury',
        price_range_min: 85000,
        price_range_max: 180000,
        price_range_typical: 120000,
        currency: 'JPY',
        avg_advantage_percent: 29,
        advantage_level: 'excellent',
        our_primary_channel: 'ikyu_b2b',
        similar_hotels: ['hoshinoya-tokyo', 'aman-kyoto'],
        alternative_hotels: ['four-seasons-kyoto'],
        upgrade_options: ['aman-kyoto'],
        budget_options: ['four-seasons-kyoto', 'hiiragiya'],
        booking_difficulty: 'hard',
        advance_booking_days: 60,
        peak_seasons: ['樱花季(3月下旬-4月上旬)', '红叶季(11月中旬-12月上旬)'],
        rooms_count: 25,
        opening_year: 2009,
        renovation_year: 2019,
        checkin_time: '15:00',
        checkout_time: '12:00',
        website: 'https://hoshinoya.com/kyoto/',
        phone: '+81-50-3134-8091',
        email: '',
        notebooklm_url: null,
        official_url: 'https://hoshinoya.com/kyoto/',
        status: '在售',
        info_completeness: 98,
        created_at: '2024-01-01',
        updated_at: '2024-12-01',
        notes_conflicts: null,
    },
    {
        hotel_id: 'four-seasons-kyoto',
        name_cn: '四季京都',
        name_en: 'Four Seasons Hotel Kyoto',
        name_local: 'フォーシーズンズホテル京都',
        brand: '四季',
        group: 'Four Seasons',
        country: '日本',
        region: '关西',
        city: '京都',
        area_tag: '东山',
        destination_board: 'kyoto-ancient',
        address_full: '京都府京都市東山区妙法院前側町445-3',
        geo_description: '东山文化遗产区，800年历史池泉庭园',
        transport_info: '京都站乘车10分钟，三十三间堂旁',
        positioning_short: '现代与日式的完美融合',
        positioning_keywords: ['池泉庭园', '茶室', '现代日式', '四季服务'],
        target_guests: ['家庭', '情侣', '四季忠粉'],
        style_tags: ['现代日式', '庭园景观', '国际品牌'],
        highlights: ['800年积翠园', '池畔茶室', 'Brasserie餐厅'],
        price_tier: 'luxury',
        price_range_min: 78000,
        price_range_max: 150000,
        price_range_typical: 88000,
        currency: 'JPY',
        avg_advantage_percent: 11,
        advantage_level: 'fair',
        our_primary_channel: 'direct',
        similar_hotels: ['ritz-carlton-kyoto', 'hoshinoya-kyoto'],
        alternative_hotels: ['hiiragiya'],
        upgrade_options: ['aman-kyoto'],
        budget_options: ['hiiragiya'],
        booking_difficulty: 'moderate',
        advance_booking_days: 30,
        peak_seasons: ['樱花季', '红叶季'],
        rooms_count: 180,
        opening_year: 2016,
        renovation_year: null,
        checkin_time: '15:00',
        checkout_time: '12:00',
        website: 'https://www.fourseasons.com/kyoto/',
        phone: '+81-75-541-8288',
        email: '',
        notebooklm_url: null,
        official_url: 'https://www.fourseasons.com/kyoto/',
        status: '在售',
        info_completeness: 90,
        created_at: '2024-01-01',
        updated_at: '2024-12-01',
        notes_conflicts: null,
    },
    {
        hotel_id: 'aman-kyoto',
        name_cn: '安缦京都',
        name_en: 'Aman Kyoto',
        name_local: 'アマン京都',
        brand: '安缦',
        group: 'Aman Resorts',
        country: '日本',
        region: '关西',
        city: '京都',
        area_tag: '北山',
        destination_board: 'kyoto-ancient',
        address_full: '京都府京都市北区大北山鷹峯町1',
        geo_description: '金阁寺后山，隐于林中的禅意秘境',
        transport_info: '京都站乘车30分钟',
        positioning_short: '森林中的禅意野奢',
        positioning_keywords: ['森林秘境', '禅意', '野奢', '安缦'],
        target_guests: ['安缦粉', '隐私需求', '自然控', 'UHNW'],
        style_tags: ['野奢', '禅意设计', '森林秘境'],
        highlights: ['原始森林环绕', '温泉', '极致隐私'],
        price_tier: 'ultra_luxury',
        price_range_min: 165000,
        price_range_max: 450000,
        price_range_typical: 198000,
        currency: 'JPY',
        avg_advantage_percent: 17,
        advantage_level: 'good',
        our_primary_channel: 'ikyu_b2b',
        similar_hotels: ['aman-tokyo', 'hoshinoya-kyoto'],
        alternative_hotels: [],
        upgrade_options: [],
        budget_options: ['hoshinoya-kyoto', 'four-seasons-kyoto'],
        booking_difficulty: 'hard',
        advance_booking_days: 60,
        peak_seasons: ['樱花季', '红叶季', '年末年始'],
        rooms_count: 26,
        opening_year: 2019,
        renovation_year: null,
        checkin_time: '15:00',
        checkout_time: '12:00',
        website: 'https://www.aman.com/hotels/aman-kyoto',
        phone: '+81-75-496-1333',
        email: '',
        notebooklm_url: null,
        official_url: 'https://www.aman.com/hotels/aman-kyoto',
        status: '在售',
        info_completeness: 95,
        created_at: '2024-01-01',
        updated_at: '2024-12-01',
        notes_conflicts: null,
    },
    {
        hotel_id: 'hiiragiya',
        name_cn: '柊家旅馆',
        name_en: 'Hiiragiya Ryokan',
        name_local: '柊家旅館',
        brand: '独立',
        group: '独立',
        country: '日本',
        region: '关西',
        city: '京都',
        area_tag: '中京',
        destination_board: 'kyoto-ancient',
        address_full: '京都府京都市中京区麩屋町姉小路上ル',
        geo_description: '京都市中心，200年历史的老铺旅馆',
        transport_info: '京都站乘车10分钟，地铁乌丸御池站步行5分钟',
        positioning_short: '传承200年的和之心',
        positioning_keywords: ['百年老铺', '传统旅馆', '日式待客', '历史'],
        target_guests: ['日式控', '文化体验', '历史爱好者'],
        style_tags: ['日式传统', '百年老铺', '怀石料理'],
        highlights: ['200年历史', '纯正怀石料理', '老女将待客'],
        price_tier: 'upper_upscale',
        price_range_min: 55000,
        price_range_max: 120000,
        price_range_typical: 58000,
        currency: 'JPY',
        avg_advantage_percent: 5,
        advantage_level: 'none',
        our_primary_channel: 'direct',
        similar_hotels: ['tawaraya', 'hoshinoya-kyoto'],
        alternative_hotels: ['four-seasons-kyoto'],
        upgrade_options: ['hoshinoya-kyoto', 'aman-kyoto'],
        budget_options: [],
        booking_difficulty: 'hard',
        advance_booking_days: 90,
        peak_seasons: ['樱花季', '红叶季', '祇園祭'],
        rooms_count: 28,
        opening_year: 1818,
        renovation_year: 2010,
        checkin_time: '14:00',
        checkout_time: '11:00',
        website: 'https://www.hiiragiya.co.jp/',
        phone: '+81-75-221-1136',
        email: '',
        notebooklm_url: null,
        official_url: 'https://www.hiiragiya.co.jp/',
        status: '在售',
        info_completeness: 85,
        created_at: '2024-01-01',
        updated_at: '2024-12-01',
        notes_conflicts: null,
    },

    // ========== 富士山周边 (3家) ==========
    {
        hotel_id: 'fufu-kawaguchiko',
        name_cn: 'FUFU河口湖',
        name_en: 'FUFU Kawaguchiko',
        name_local: 'ふふ河口湖',
        brand: 'FUFU',
        group: 'カトープレジャーグループ',
        country: '日本',
        region: '中部',
        city: '河口湖',
        area_tag: '河口湖',
        destination_board: 'fuji-area',
        address_full: '山梨県南都留郡富士河口湖町河口字水口2211-1',
        geo_description: '河口湖畔，正对富士山的绝景位置',
        transport_info: '河口湖站乘车10分钟，有免费接送',
        positioning_short: '富士山下的温泉私汤',
        positioning_keywords: ['富士山景', '温泉私汤', '设计感', '静谧'],
        target_guests: ['蜜月', '温泉控', '摄影师'],
        style_tags: ['现代设计', '温泉私汤', '富士山景'],
        highlights: ['全房型私汤', '富士山正面景', '设计感强'],
        price_tier: 'upper_upscale',
        price_range_min: 52000,
        price_range_max: 98000,
        price_range_typical: 72000,
        currency: 'JPY',
        avg_advantage_percent: 28,
        advantage_level: 'excellent',
        our_primary_channel: 'ikyu_b2b',
        similar_hotels: ['hoshinoya-fuji', 'konansou'],
        alternative_hotels: ['fugaku'],
        upgrade_options: ['hoshinoya-fuji'],
        budget_options: ['fugaku'],
        booking_difficulty: 'moderate',
        advance_booking_days: 45,
        peak_seasons: ['元旦富士初日出', '冬季雪景', '秋季红叶'],
        rooms_count: 32,
        opening_year: 2018,
        renovation_year: null,
        checkin_time: '15:00',
        checkout_time: '11:00',
        website: 'https://www.fufuhotels.jp/kawaguchiko/',
        phone: '+81-555-73-9573',
        email: '',
        notebooklm_url: null,
        official_url: 'https://www.fufuhotels.jp/kawaguchiko/',
        status: '在售',
        info_completeness: 92,
        created_at: '2024-01-01',
        updated_at: '2024-12-01',
        notes_conflicts: null,
    },
    {
        hotel_id: 'hoshinoya-fuji',
        name_cn: '虹夕诺雅 富士',
        name_en: 'Hoshinoya Fuji',
        name_local: '星のや富士',
        brand: '虹夕诺雅',
        group: '星野集团',
        country: '日本',
        region: '中部',
        city: '河口湖',
        area_tag: '河口湖',
        destination_board: 'fuji-area',
        address_full: '山梨県南都留郡富士河口湖町大石1408',
        geo_description: '河口湖北岸山腰，日本首家野奢度假村',
        transport_info: '河口湖站乘车20分钟，有免费接送',
        positioning_short: '日本首家野奢露营',
        positioning_keywords: ['野奢露营', '户外体验', '富士山景', 'Glamping'],
        target_guests: ['户外爱好者', '情侣', '年轻客群'],
        style_tags: ['野奢', 'Glamping', '户外体验'],
        highlights: ['日本首家Glamping', '云上露台', '户外活动丰富'],
        price_tier: 'luxury',
        price_range_min: 68000,
        price_range_max: 120000,
        price_range_typical: 95000,
        currency: 'JPY',
        avg_advantage_percent: 28,
        advantage_level: 'excellent',
        our_primary_channel: 'ikyu_b2b',
        similar_hotels: ['fufu-kawaguchiko', 'hoshinoya-kyoto'],
        alternative_hotels: ['fufu-kawaguchiko'],
        upgrade_options: [],
        budget_options: ['fufu-kawaguchiko', 'fugaku'],
        booking_difficulty: 'moderate',
        advance_booking_days: 45,
        peak_seasons: ['元旦', '夏季', '秋季'],
        rooms_count: 40,
        opening_year: 2015,
        renovation_year: null,
        checkin_time: '15:00',
        checkout_time: '12:00',
        website: 'https://hoshinoya.com/fuji/',
        phone: '+81-50-3134-8091',
        email: '',
        notebooklm_url: null,
        official_url: 'https://hoshinoya.com/fuji/',
        status: '在售',
        info_completeness: 90,
        created_at: '2024-01-01',
        updated_at: '2024-12-01',
        notes_conflicts: null,
    },
    {
        hotel_id: 'fugaku',
        name_cn: '富士吟景',
        name_en: 'Fugaku Ginkei',
        name_local: '富岳吟景',
        brand: '独立',
        group: '独立',
        country: '日本',
        region: '中部',
        city: '河口湖',
        area_tag: '河口湖',
        destination_board: 'fuji-area',
        address_full: '山梨県南都留郡富士河口湖町浅川132',
        geo_description: '河口湖温泉乡，性价比之选',
        transport_info: '河口湖站步行15分钟或乘车5分钟',
        positioning_short: '性价比温泉之选',
        positioning_keywords: ['性价比', '温泉', '家庭友好', '富士山景'],
        target_guests: ['家庭', '预算敏感', '温泉入门'],
        style_tags: ['传统温泉', '性价比', '家庭友好'],
        highlights: ['富士山景房', '公共温泉大浴场', '性价比高'],
        price_tier: 'upscale',
        price_range_min: 35000,
        price_range_max: 65000,
        price_range_typical: 42000,
        currency: 'JPY',
        avg_advantage_percent: 17,
        advantage_level: 'good',
        our_primary_channel: 'jalan_b2b',
        similar_hotels: ['konansou'],
        alternative_hotels: ['fufu-kawaguchiko'],
        upgrade_options: ['fufu-kawaguchiko', 'hoshinoya-fuji'],
        budget_options: [],
        booking_difficulty: 'easy',
        advance_booking_days: 14,
        peak_seasons: ['元旦', '黄金周'],
        rooms_count: 45,
        opening_year: 1985,
        renovation_year: 2018,
        checkin_time: '15:00',
        checkout_time: '10:00',
        website: 'https://fugaku-ginkei.jp/',
        phone: '+81-555-72-5002',
        email: '',
        notebooklm_url: null,
        official_url: 'https://fugaku-ginkei.jp/',
        status: '在售',
        info_completeness: 80,
        created_at: '2024-01-01',
        updated_at: '2024-12-01',
        notes_conflicts: null,
    },

    // ========== 北海道 (3家) ==========
    {
        hotel_id: 'zaborin',
        name_cn: '坐忘林',
        name_en: 'Zaborin',
        name_local: '坐忘林',
        brand: '坐忘林',
        group: '独立',
        country: '日本',
        region: '北海道',
        city: '二世古',
        area_tag: '花园',
        destination_board: 'hokkaido',
        address_full: '北海道虻田郡倶知安町花園76-4',
        geo_description: '二世古滑雪区后山，隐世温泉秘境',
        transport_info: '新千�的机场乘车2小时，二世古站乘车20分钟',
        positioning_short: '北国温泉秘境',
        positioning_keywords: ['温泉秘境', '隐世', '设计感', '粉雪'],
        target_guests: ['蜜月', '滑雪', '设计控'],
        style_tags: ['现代设计', '温泉秘境', '北国风情'],
        highlights: ['全房型私汤', '羊蹄山景', '设计大师作品'],
        price_tier: 'luxury',
        price_range_min: 72000,
        price_range_max: 150000,
        price_range_typical: 98000,
        currency: 'JPY',
        avg_advantage_percent: 27,
        advantage_level: 'excellent',
        our_primary_channel: 'ikyu_b2b',
        similar_hotels: ['bourou-noguchi', 'hoshinoya-kyoto'],
        alternative_hotels: ['bourou-noguchi'],
        upgrade_options: [],
        budget_options: ['bourou-noguchi', 'tsuruga-resort'],
        booking_difficulty: 'hard',
        advance_booking_days: 60,
        peak_seasons: ['滑雪季(12月-3月)', '夏季避暑'],
        rooms_count: 15,
        opening_year: 2015,
        renovation_year: null,
        checkin_time: '15:00',
        checkout_time: '11:00',
        website: 'https://zaborin.com/',
        phone: '+81-136-23-0003',
        email: '',
        notebooklm_url: null,
        official_url: 'https://zaborin.com/',
        status: '在售',
        info_completeness: 93,
        created_at: '2024-01-01',
        updated_at: '2024-12-01',
        notes_conflicts: null,
    },
    {
        hotel_id: 'bourou-noguchi',
        name_cn: '望楼NOGUCHI',
        name_en: 'Bourou Noguchi Noboribetsu',
        name_local: '望楼NOGUCHI登別',
        brand: '望楼NOGUCHI',
        group: '野口観光',
        country: '日本',
        region: '北海道',
        city: '登别',
        area_tag: '登别温泉',
        destination_board: 'hokkaido',
        address_full: '北海道登別市登別温泉町200-1',
        geo_description: '登别温泉乡核心，设计与温泉的完美结合',
        transport_info: '新千岁机场乘车1.5小时，登别站乘车15分钟',
        positioning_short: '设计感温泉体验',
        positioning_keywords: ['设计温泉', '登别', '私汤', '现代日式'],
        target_guests: ['情侣', '设计控', '温泉入门'],
        style_tags: ['现代设计', '温泉', '私汤体验'],
        highlights: ['全房型展望风吕', '设计感强', '怀石料理'],
        price_tier: 'upper_upscale',
        price_range_min: 55000,
        price_range_max: 98000,
        price_range_typical: 72000,
        currency: 'JPY',
        avg_advantage_percent: 24,
        advantage_level: 'good',
        our_primary_channel: 'ikyu_b2b',
        similar_hotels: ['zaborin', 'fufu-kawaguchiko'],
        alternative_hotels: ['tsuruga-resort'],
        upgrade_options: ['zaborin'],
        budget_options: ['tsuruga-resort'],
        booking_difficulty: 'moderate',
        advance_booking_days: 30,
        peak_seasons: ['滑雪季', '夏季'],
        rooms_count: 42,
        opening_year: 2008,
        renovation_year: 2020,
        checkin_time: '14:00',
        checkout_time: '11:00',
        website: 'https://www.bourou.com/',
        phone: '+81-143-84-3939',
        email: '',
        notebooklm_url: null,
        official_url: 'https://www.bourou.com/',
        status: '在售',
        info_completeness: 88,
        created_at: '2024-01-01',
        updated_at: '2024-12-01',
        notes_conflicts: null,
    },
    {
        hotel_id: 'tsuruga-resort',
        name_cn: '鶴雅度假酒店',
        name_en: 'Tsuruga Resort Spa Hanayuuka',
        name_local: '鶴雅リゾートスパ 花ゆう香',
        brand: '鶴雅',
        group: '鶴雅集团',
        country: '日本',
        region: '北海道',
        city: '阿寒湖',
        area_tag: '阿寒湖温泉',
        destination_board: 'hokkaido',
        address_full: '北海道釧路市阿寒町阿寒湖温泉1-6-1',
        geo_description: '阿寒湖畔，亲子友好的综合度假村',
        transport_info: '�的路机场乘车1小时',
        positioning_short: '亲子友好综合度假',
        positioning_keywords: ['亲子', '综合度假', '阿寒湖', '自然'],
        target_guests: ['亲子', '家庭', '自然爱好者'],
        style_tags: ['综合度假', '家庭友好', '湖景'],
        highlights: ['阿寒湖畔', '亲子设施丰富', '阿伊努文化体验'],
        price_tier: 'upscale',
        price_range_min: 38000,
        price_range_max: 75000,
        price_range_typical: 45000,
        currency: 'JPY',
        avg_advantage_percent: 16,
        advantage_level: 'good',
        our_primary_channel: 'jalan_b2b',
        similar_hotels: ['hoshino-tomamu'],
        alternative_hotels: ['bourou-noguchi'],
        upgrade_options: ['bourou-noguchi', 'zaborin'],
        budget_options: [],
        booking_difficulty: 'easy',
        advance_booking_days: 14,
        peak_seasons: ['冬季', '夏季'],
        rooms_count: 120,
        opening_year: 2000,
        renovation_year: 2019,
        checkin_time: '15:00',
        checkout_time: '10:00',
        website: 'https://www.tsurugagroup.com/',
        phone: '+81-154-67-4000',
        email: '',
        notebooklm_url: null,
        official_url: 'https://www.tsurugagroup.com/',
        status: '在售',
        info_completeness: 82,
        created_at: '2024-01-01',
        updated_at: '2024-12-01',
        notes_conflicts: null,
    },
];

// === Helper Functions ===
export function getHotelsByBoard(boardId: string): Hotel[] {
    return hotels.filter(h => h.destination_board === boardId);
}

export function getHotelById(hotelId: string): Hotel | undefined {
    return hotels.find(h => h.hotel_id === hotelId);
}

export function getBoardById(boardId: string): DestinationBoard | undefined {
    return destinationBoards.find(b => b.board_id === boardId);
}

export function getAdvantageHotels(): Hotel[] {
    return hotels.filter(h => h.advantage_level === 'excellent' || h.advantage_level === 'good');
}
