// ============================================
// Luxury Ops - Mock Inquiries Data
// ============================================

import { Inquiry, InquiryStage, RecommendationWeights } from '@/lib/types';

const defaultWeights: RecommendationWeights = {
    price_advantage: 0.25,
    budget_match: 0.25,
    guest_fit: 0.20,
    availability: 0.20,
    booking_ease: 0.10,
};

export const mockInquiries: Inquiry[] = [
    {
        inquiry_id: 'inq-001',
        customer_name: '张先生',
        customer_contact: '138****5678',
        customer_wechat: 'zhang_san_travel',
        customer_tags: ['高净值', '回头客', '喜欢日式'],
        destinations: ['京都', '东京'],
        travel_dates: {
            from: '2025-04-01',
            to: '2025-04-05',
            nights: 4,
            flexible: true,
            flexible_range: 3,
        },
        travelers: {
            adults: 2,
            children: 0,
            children_ages: [],
            infants: 0,
        },
        budget_per_night: {
            min: 80000,
            max: 150000,
            currency: 'JPY',
            flexible: true,
        },
        style_preferences: ['日式传统', '温泉', '隐私'],
        must_have: ['私汤', '怀石料理'],
        nice_to_have: ['管家服务', '接送机'],
        avoid: ['商务酒店', '太吵闹'],
        special_requests: '蜜月旅行，希望有惊喜布置',
        special_occasion: '蜜月',
        recommended_hotels: [
            {
                hotel_id: 'hoshinoya-kyoto',
                room_type_id: null,
                dates: { from: '2025-04-01', to: '2025-04-03' },
                quoted_price: 280000,
                recommended_at: '2024-12-28T10:00:00Z',
                customer_feedback: 'interested',
                feedback_note: '客人很感兴趣，问了房型细节',
            },
        ],
        stage: '方案推荐',
        priority: 'VIP',
        source: '微信',
        assigned_to: '小王',
        recommendation_weights: defaultWeights,
        created_at: '2024-12-27T09:00:00Z',
        updated_at: '2024-12-28T10:30:00Z',
        notes: '老客户转介绍，预算充足，要求品质',
    },
    {
        inquiry_id: 'inq-002',
        customer_name: '李女士',
        customer_contact: '139****1234',
        customer_wechat: 'li_travel_2024',
        customer_tags: ['亲子游', '首次日本'],
        destinations: ['富士山', '东京'],
        travel_dates: {
            from: '2025-01-20',
            to: '2025-01-25',
            nights: 5,
            flexible: false,
            flexible_range: 0,
        },
        travelers: {
            adults: 2,
            children: 2,
            children_ages: [5, 8],
            infants: 0,
        },
        budget_per_night: {
            min: 50000,
            max: 80000,
            currency: 'JPY',
            flexible: false,
        },
        style_preferences: ['亲子友好', '温泉', '自然'],
        must_have: ['儿童设施', '和室'],
        nice_to_have: ['儿童餐', '温泉大浴场'],
        avoid: ['纯成人酒店'],
        special_requests: '孩子第一次看雪，希望有雪景',
        special_occasion: null,
        recommended_hotels: [],
        stage: '需求确认',
        priority: '普通',
        source: '电话',
        assigned_to: '小李',
        recommendation_weights: defaultWeights,
        created_at: '2024-12-28T14:00:00Z',
        updated_at: '2024-12-28T14:00:00Z',
        notes: '预算有限，需要性价比高的选择',
    },
    {
        inquiry_id: 'inq-003',
        customer_name: '王总',
        customer_contact: '137****9999',
        customer_wechat: 'wang_ceo',
        customer_tags: ['UHNW', '安缦粉', '隐私要求高'],
        destinations: ['京都'],
        travel_dates: {
            from: '2025-03-25',
            to: '2025-03-30',
            nights: 5,
            flexible: true,
            flexible_range: 5,
        },
        travelers: {
            adults: 2,
            children: 0,
            children_ages: [],
            infants: 0,
        },
        budget_per_night: {
            min: 150000,
            max: 500000,
            currency: 'JPY',
            flexible: true,
        },
        style_preferences: ['极简设计', '隐私', '自然'],
        must_have: ['安缦品牌', '私汤'],
        nice_to_have: ['直升机接送', '私人导游'],
        avoid: ['商务酒店', '人多的地方'],
        special_requests: '樱花季，要求最私密的房型',
        special_occasion: '结婚10周年',
        recommended_hotels: [
            {
                hotel_id: 'aman-kyoto',
                room_type_id: null,
                dates: { from: '2025-03-25', to: '2025-03-30' },
                quoted_price: 950000,
                recommended_at: '2024-12-27T16:00:00Z',
                customer_feedback: 'considering',
                feedback_note: '在考虑，问了其他安缦的情况',
            },
        ],
        stage: '等待反馈',
        priority: 'VIP',
        source: '转介绍',
        assigned_to: '小王',
        recommendation_weights: { ...defaultWeights, price_advantage: 0.10, guest_fit: 0.35 },
        created_at: '2024-12-26T11:00:00Z',
        updated_at: '2024-12-28T09:00:00Z',
        notes: '朋友介绍，预算无上限，只要求品质',
    },
    {
        inquiry_id: 'inq-004',
        customer_name: '陈小姐',
        customer_contact: '136****5555',
        customer_wechat: 'chen_miss',
        customer_tags: ['闺蜜游', '打卡族'],
        destinations: ['东京', '京都'],
        travel_dates: {
            from: '2025-02-10',
            to: '2025-02-14',
            nights: 4,
            flexible: true,
            flexible_range: 2,
        },
        travelers: {
            adults: 3,
            children: 0,
            children_ages: [],
            infants: 0,
        },
        budget_per_night: {
            min: 40000,
            max: 70000,
            currency: 'JPY',
            flexible: true,
        },
        style_preferences: ['设计感', '拍照好看', '便利'],
        must_have: ['交通便利', '房间大'],
        nice_to_have: ['屋顶酒吧', '城市景观'],
        avoid: ['太传统', '偏僻'],
        special_requests: '3人同住，希望房间够大',
        special_occasion: null,
        recommended_hotels: [
            {
                hotel_id: 'park-hyatt-tokyo',
                room_type_id: null,
                dates: { from: '2025-02-10', to: '2025-02-12' },
                quoted_price: 120000,
                recommended_at: '2024-12-28T11:00:00Z',
                customer_feedback: 'not_interested',
                feedback_note: '觉得太商务了',
            },
            {
                hotel_id: 'hoshinoya-tokyo',
                room_type_id: null,
                dates: { from: '2025-02-10', to: '2025-02-12' },
                quoted_price: 180000,
                recommended_at: '2024-12-28T15:00:00Z',
                customer_feedback: 'interested',
                feedback_note: '很感兴趣，问了拍照角度',
            },
        ],
        stage: '确认预订',
        priority: '紧急',
        source: '微信',
        assigned_to: '小李',
        recommendation_weights: defaultWeights,
        created_at: '2024-12-27T20:00:00Z',
        updated_at: '2024-12-28T16:00:00Z',
        notes: '急需确认，客人明天要付款',
    },
    {
        inquiry_id: 'inq-005',
        customer_name: '刘先生',
        customer_contact: '135****7777',
        customer_wechat: 'liu_business',
        customer_tags: ['商务', '高频出差'],
        destinations: ['东京'],
        travel_dates: {
            from: '2025-01-15',
            to: '2025-01-17',
            nights: 2,
            flexible: false,
            flexible_range: 0,
        },
        travelers: {
            adults: 1,
            children: 0,
            children_ages: [],
            infants: 0,
        },
        budget_per_night: {
            min: 50000,
            max: 100000,
            currency: 'JPY',
            flexible: false,
        },
        style_preferences: ['商务', '便利', '安静'],
        must_have: ['商务中心', '健身房'],
        nice_to_have: ['行政酒廊', '机场快线'],
        avoid: ['太花哨'],
        special_requests: '需要发票',
        special_occasion: null,
        recommended_hotels: [
            {
                hotel_id: 'peninsula-tokyo',
                room_type_id: null,
                dates: { from: '2025-01-15', to: '2025-01-17' },
                quoted_price: 150000,
                recommended_at: '2024-12-28T09:00:00Z',
                customer_feedback: 'booked',
                feedback_note: '已确认预订',
            },
        ],
        stage: '订房中',
        priority: '普通',
        source: '邮件',
        assigned_to: '小王',
        recommendation_weights: defaultWeights,
        created_at: '2024-12-28T08:00:00Z',
        updated_at: '2024-12-28T17:00:00Z',
        notes: '老客户，每月都有出差需求',
    },
];

// Helper functions
export function getInquiriesByStage(stage: InquiryStage): Inquiry[] {
    return mockInquiries.filter(inq => inq.stage === stage);
}

export function getInquiryById(id: string): Inquiry | undefined {
    return mockInquiries.find(inq => inq.inquiry_id === id);
}

export const inquiryStages: InquiryStage[] = [
    '需求确认',
    '方案推荐',
    '等待反馈',
    '确认预订',
    '订房中',
    '已完成',
    '已流失',
    '已取消',
];

export const activeStages: InquiryStage[] = [
    '需求确认',
    '方案推荐',
    '等待反馈',
    '确认预订',
    '订房中',
];
