// ============================================
// Luxury Ops - Room Types Mock Data
// ============================================

import { RoomType } from '@/lib/types';

// Room types for each hotel
export const roomTypes: RoomType[] = [
    // ===== 虹夕诺雅 东京 =====
    {
        room_id: 'hoshinoya-tokyo-kiku',
        hotel_id: 'hoshinoya-tokyo',
        room_name_cn: '菊 - 标准客房',
        room_name_en: 'Kiku Room',
        room_name_local: '菊',
        room_code_internal: 'KIKU',
        is_main_selling: true,
        is_entry_level: true,
        is_signature: false,
        recommendation_priority: 3,
        area_min_sqm: 50,
        area_max_sqm: 50,
        bed_type: '双人床',
        max_adults: 2,
        max_children: 1,
        max_occupancy: 3,
        view_type: '城景',
        has_balcony: false,
        has_onsen: true,
        has_living_room: false,
        is_connectable: false,
        is_smoking: false,
        floor_info: '3-10层',
        highlights: ['榻榻米设计', '私人温泉浴', '日式极简美学'],
        suitable_for: ['情侣', '商务'],
        weekday_rate_min: 85000,
        weekday_rate_max: 95000,
        weekend_rate_min: 105000,
        weekend_rate_max: 125000,
        currency: 'JPY',
        rate_note: '含早餐',
        avg_advantage_percent: 18,
        advantage_level: 'good',
        is_high_profit: true,
        hero_image_url: '',
        gallery_urls: [],
        floorplan_url: null,
        created_at: '2024-01-01',
        updated_at: '2024-01-01',
    },
    {
        room_id: 'hoshinoya-tokyo-kikyo',
        hotel_id: 'hoshinoya-tokyo',
        room_name_cn: '桔梗 - 豪华客房',
        room_name_en: 'Kikyo Room',
        room_name_local: '桔梗',
        room_code_internal: 'KIKYO',
        is_main_selling: true,
        is_entry_level: false,
        is_signature: false,
        recommendation_priority: 2,
        area_min_sqm: 65,
        area_max_sqm: 65,
        bed_type: '双人床',
        max_adults: 2,
        max_children: 2,
        max_occupancy: 4,
        view_type: '城景',
        has_balcony: false,
        has_onsen: true,
        has_living_room: true,
        is_connectable: true,
        is_smoking: false,
        floor_info: '11-15层',
        highlights: ['独立起居区', '高楼层景观', '宽敞浴室'],
        suitable_for: ['家庭', '情侣'],
        weekday_rate_min: 120000,
        weekday_rate_max: 135000,
        weekend_rate_min: 145000,
        weekend_rate_max: 165000,
        currency: 'JPY',
        rate_note: '含早餐',
        avg_advantage_percent: 22,
        advantage_level: 'good',
        is_high_profit: true,
        hero_image_url: '',
        gallery_urls: [],
        floorplan_url: null,
        created_at: '2024-01-01',
        updated_at: '2024-01-01',
    },
    {
        room_id: 'hoshinoya-tokyo-sakura',
        hotel_id: 'hoshinoya-tokyo',
        room_name_cn: '樱 - 套房',
        room_name_en: 'Sakura Suite',
        room_name_local: '桜',
        room_code_internal: 'SAKURA',
        is_main_selling: false,
        is_entry_level: false,
        is_signature: true,
        recommendation_priority: 1,
        area_min_sqm: 90,
        area_max_sqm: 90,
        bed_type: '特大床',
        max_adults: 2,
        max_children: 2,
        max_occupancy: 4,
        view_type: '皇居景',
        has_balcony: false,
        has_onsen: true,
        has_living_room: true,
        is_connectable: false,
        is_smoking: false,
        floor_info: '16-17层',
        highlights: ['顶层皇居景观', '超大私汤', '专属管家'],
        suitable_for: ['蜜月', 'VIP', '特殊纪念日'],
        weekday_rate_min: 180000,
        weekday_rate_max: 200000,
        weekend_rate_min: 220000,
        weekend_rate_max: 250000,
        currency: 'JPY',
        rate_note: '含早餐+下午茶',
        avg_advantage_percent: 25,
        advantage_level: 'excellent',
        is_high_profit: true,
        hero_image_url: '',
        gallery_urls: [],
        floorplan_url: null,
        created_at: '2024-01-01',
        updated_at: '2024-01-01',
    },

    // ===== 虹夕诺雅 京都 =====
    {
        room_id: 'hoshinoya-kyoto-tsuki',
        hotel_id: 'hoshinoya-kyoto',
        room_name_cn: '月桥 - 河景房',
        room_name_en: 'Tsukihashi',
        room_name_local: '月橋',
        room_code_internal: 'TSUKI',
        is_main_selling: true,
        is_entry_level: true,
        is_signature: false,
        recommendation_priority: 3,
        area_min_sqm: 41,
        area_max_sqm: 65,
        bed_type: '双人床',
        max_adults: 2,
        max_children: 1,
        max_occupancy: 3,
        view_type: '大堰川景',
        has_balcony: true,
        has_onsen: false,
        has_living_room: false,
        is_connectable: false,
        is_smoking: false,
        floor_info: '水边',
        highlights: ['临水而建', '传统町屋风格', '静谧河景'],
        suitable_for: ['情侣', '文艺青年'],
        weekday_rate_min: 75000,
        weekday_rate_max: 95000,
        weekend_rate_min: 95000,
        weekend_rate_max: 115000,
        currency: 'JPY',
        rate_note: '含早餐+接驳船',
        avg_advantage_percent: 28,
        advantage_level: 'excellent',
        is_high_profit: true,
        hero_image_url: '',
        gallery_urls: [],
        floorplan_url: null,
        created_at: '2024-01-01',
        updated_at: '2024-01-01',
    },
    {
        room_id: 'hoshinoya-kyoto-yama',
        hotel_id: 'hoshinoya-kyoto',
        room_name_cn: '山之端 - 庭院房',
        room_name_en: 'Yamanohata',
        room_name_local: '山の端',
        room_code_internal: 'YAMA',
        is_main_selling: true,
        is_entry_level: false,
        is_signature: false,
        recommendation_priority: 2,
        area_min_sqm: 65,
        area_max_sqm: 100,
        bed_type: '双人床',
        max_adults: 2,
        max_children: 2,
        max_occupancy: 4,
        view_type: '山景+庭院',
        has_balcony: true,
        has_onsen: false,
        has_living_room: true,
        is_connectable: true,
        is_smoking: false,
        floor_info: '山侧',
        highlights: ['私人庭院', '双面采光', '茶室空间'],
        suitable_for: ['家庭', '长辈'],
        weekday_rate_min: 110000,
        weekday_rate_max: 130000,
        weekend_rate_min: 135000,
        weekend_rate_max: 160000,
        currency: 'JPY',
        rate_note: '含早餐+接驳船',
        avg_advantage_percent: 30,
        advantage_level: 'excellent',
        is_high_profit: true,
        hero_image_url: '',
        gallery_urls: [],
        floorplan_url: null,
        created_at: '2024-01-01',
        updated_at: '2024-01-01',
    },
    {
        room_id: 'hoshinoya-kyoto-mizunoki',
        hotel_id: 'hoshinoya-kyoto',
        room_name_cn: '水之庭 - 独栋别墅',
        room_name_en: 'Mizunoki Villa',
        room_name_local: '水の棲',
        room_code_internal: 'MIZU',
        is_main_selling: false,
        is_entry_level: false,
        is_signature: true,
        recommendation_priority: 1,
        area_min_sqm: 150,
        area_max_sqm: 150,
        bed_type: '特大床',
        max_adults: 2,
        max_children: 2,
        max_occupancy: 4,
        view_type: '河景全景',
        has_balcony: true,
        has_onsen: true,
        has_living_room: true,
        is_connectable: false,
        is_smoking: false,
        floor_info: '独栋',
        highlights: ['独栋别墅', '私人露天温泉', '管家服务', '最佳河景'],
        suitable_for: ['蜜月', 'VIP', '隐私需求'],
        weekday_rate_min: 280000,
        weekday_rate_max: 320000,
        weekend_rate_min: 350000,
        weekend_rate_max: 400000,
        currency: 'JPY',
        rate_note: '含早晚餐+专属管家',
        avg_advantage_percent: 32,
        advantage_level: 'excellent',
        is_high_profit: true,
        hero_image_url: '',
        gallery_urls: [],
        floorplan_url: null,
        created_at: '2024-01-01',
        updated_at: '2024-01-01',
    },

    // ===== FUFU河口湖 =====
    {
        room_id: 'fufu-kawaguchiko-standard',
        hotel_id: 'fufu-kawaguchiko',
        room_name_cn: '富士景观房',
        room_name_en: 'Mt. Fuji View Room',
        room_name_local: '富士ビュー',
        room_code_internal: 'FV',
        is_main_selling: true,
        is_entry_level: true,
        is_signature: false,
        recommendation_priority: 3,
        area_min_sqm: 55,
        area_max_sqm: 65,
        bed_type: '双人床',
        max_adults: 2,
        max_children: 1,
        max_occupancy: 3,
        view_type: '富士山景',
        has_balcony: true,
        has_onsen: true,
        has_living_room: false,
        is_connectable: false,
        is_smoking: false,
        floor_info: '2-4层',
        highlights: ['私人露天温泉', '富士山正对面', '极简现代设计'],
        suitable_for: ['情侣', '朝圣富士山'],
        weekday_rate_min: 65000,
        weekday_rate_max: 75000,
        weekend_rate_min: 85000,
        weekend_rate_max: 100000,
        currency: 'JPY',
        rate_note: '含早晚餐',
        avg_advantage_percent: 25,
        advantage_level: 'excellent',
        is_high_profit: true,
        hero_image_url: '',
        gallery_urls: [],
        floorplan_url: null,
        created_at: '2024-01-01',
        updated_at: '2024-01-01',
    },
    {
        room_id: 'fufu-kawaguchiko-suite',
        hotel_id: 'fufu-kawaguchiko',
        room_name_cn: '富士套房',
        room_name_en: 'Mt. Fuji Suite',
        room_name_local: '富士スイート',
        room_code_internal: 'FS',
        is_main_selling: true,
        is_entry_level: false,
        is_signature: true,
        recommendation_priority: 1,
        area_min_sqm: 85,
        area_max_sqm: 100,
        bed_type: '特大床',
        max_adults: 2,
        max_children: 2,
        max_occupancy: 4,
        view_type: '富士山全景',
        has_balcony: true,
        has_onsen: true,
        has_living_room: true,
        is_connectable: false,
        is_smoking: false,
        floor_info: '顶层',
        highlights: ['超大露天私汤', '富士山最佳角度', '独立客厅'],
        suitable_for: ['蜜月', 'VIP', '摄影爱好者'],
        weekday_rate_min: 110000,
        weekday_rate_max: 130000,
        weekend_rate_min: 140000,
        weekend_rate_max: 170000,
        currency: 'JPY',
        rate_note: '含早晚餐+欢迎礼',
        avg_advantage_percent: 28,
        advantage_level: 'excellent',
        is_high_profit: true,
        hero_image_url: '',
        gallery_urls: [],
        floorplan_url: null,
        created_at: '2024-01-01',
        updated_at: '2024-01-01',
    },

    // ===== 安缦京都 =====
    {
        room_id: 'aman-kyoto-pavilion',
        hotel_id: 'aman-kyoto',
        room_name_cn: '森林小屋',
        room_name_en: 'Forest Pavilion',
        room_name_local: 'フォレストパビリオン',
        room_code_internal: 'FP',
        is_main_selling: true,
        is_entry_level: true,
        is_signature: false,
        recommendation_priority: 3,
        area_min_sqm: 72,
        area_max_sqm: 72,
        bed_type: '特大床',
        max_adults: 2,
        max_children: 1,
        max_occupancy: 3,
        view_type: '森林景',
        has_balcony: true,
        has_onsen: true,
        has_living_room: false,
        is_connectable: false,
        is_smoking: false,
        floor_info: '独栋',
        highlights: ['隐于森林', '私人日式浴池', '落地玻璃窗'],
        suitable_for: ['隐私需求', '自然爱好者'],
        weekday_rate_min: 180000,
        weekday_rate_max: 200000,
        weekend_rate_min: 220000,
        weekend_rate_max: 250000,
        currency: 'JPY',
        rate_note: '含早餐',
        avg_advantage_percent: 15,
        advantage_level: 'good',
        is_high_profit: true,
        hero_image_url: '',
        gallery_urls: [],
        floorplan_url: null,
        created_at: '2024-01-01',
        updated_at: '2024-01-01',
    },
    {
        room_id: 'aman-kyoto-sora',
        hotel_id: 'aman-kyoto',
        room_name_cn: '天空套房',
        room_name_en: 'Sora Suite',
        room_name_local: '空スイート',
        room_code_internal: 'SORA',
        is_main_selling: false,
        is_entry_level: false,
        is_signature: true,
        recommendation_priority: 1,
        area_min_sqm: 170,
        area_max_sqm: 170,
        bed_type: '特大床',
        max_adults: 2,
        max_children: 2,
        max_occupancy: 4,
        view_type: '森林+天空',
        has_balcony: true,
        has_onsen: true,
        has_living_room: true,
        is_connectable: false,
        is_smoking: false,
        floor_info: '山顶',
        highlights: ['安缦旗舰套房', '双层设计', '360度森林景', '私人管家'],
        suitable_for: ['UHNW', '蜜月', '特殊纪念日'],
        weekday_rate_min: 450000,
        weekday_rate_max: 500000,
        weekend_rate_min: 550000,
        weekend_rate_max: 650000,
        currency: 'JPY',
        rate_note: '含早晚餐+专属管家+接送',
        avg_advantage_percent: 18,
        advantage_level: 'good',
        is_high_profit: true,
        hero_image_url: '',
        gallery_urls: [],
        floorplan_url: null,
        created_at: '2024-01-01',
        updated_at: '2024-01-01',
    },

    // ===== 坐忘林 =====
    {
        room_id: 'zaborin-standard',
        hotel_id: 'zaborin',
        room_name_cn: '和洋室',
        room_name_en: 'Japanese-Western Room',
        room_name_local: '和洋室',
        room_code_internal: 'WY',
        is_main_selling: true,
        is_entry_level: true,
        is_signature: false,
        recommendation_priority: 3,
        area_min_sqm: 102,
        area_max_sqm: 102,
        bed_type: '双人床+榻榻米',
        max_adults: 2,
        max_children: 2,
        max_occupancy: 4,
        view_type: '森林景',
        has_balcony: true,
        has_onsen: true,
        has_living_room: true,
        is_connectable: false,
        is_smoking: false,
        floor_info: '独栋',
        highlights: ['私人露天温泉', '和洋结合设计', '北海道原生林'],
        suitable_for: ['情侣', '温泉控'],
        weekday_rate_min: 80000,
        weekday_rate_max: 95000,
        weekend_rate_min: 100000,
        weekend_rate_max: 120000,
        currency: 'JPY',
        rate_note: '含早晚餐',
        avg_advantage_percent: 22,
        advantage_level: 'good',
        is_high_profit: true,
        hero_image_url: '',
        gallery_urls: [],
        floorplan_url: null,
        created_at: '2024-01-01',
        updated_at: '2024-01-01',
    },
    {
        room_id: 'zaborin-suite',
        hotel_id: 'zaborin',
        room_name_cn: '坐忘套房',
        room_name_en: 'Zaborin Suite',
        room_name_local: '坐忘スイート',
        room_code_internal: 'ZS',
        is_main_selling: false,
        is_entry_level: false,
        is_signature: true,
        recommendation_priority: 1,
        area_min_sqm: 203,
        area_max_sqm: 203,
        bed_type: '特大床+榻榻米',
        max_adults: 4,
        max_children: 2,
        max_occupancy: 6,
        view_type: '森林全景',
        has_balcony: true,
        has_onsen: true,
        has_living_room: true,
        is_connectable: false,
        is_smoking: false,
        floor_info: '独栋',
        highlights: ['双卧室设计', '超大露天温泉', '可住6人', '最隐秘位置'],
        suitable_for: ['多代家庭', 'VIP', '大家庭'],
        weekday_rate_min: 150000,
        weekday_rate_max: 180000,
        weekend_rate_min: 200000,
        weekend_rate_max: 250000,
        currency: 'JPY',
        rate_note: '含早晚餐',
        avg_advantage_percent: 25,
        advantage_level: 'excellent',
        is_high_profit: true,
        hero_image_url: '',
        gallery_urls: [],
        floorplan_url: null,
        created_at: '2024-01-01',
        updated_at: '2024-01-01',
    },

    // ===== 安缦东京 =====
    {
        room_id: 'aman-tokyo-deluxe',
        hotel_id: 'aman-tokyo',
        room_name_cn: '豪华客房',
        room_name_en: 'Deluxe Room',
        room_name_local: 'デラックスルーム',
        room_code_internal: 'DX',
        is_main_selling: true,
        is_entry_level: true,
        is_signature: false,
        recommendation_priority: 3,
        area_min_sqm: 71,
        area_max_sqm: 71,
        bed_type: '特大床',
        max_adults: 2,
        max_children: 1,
        max_occupancy: 3,
        view_type: '城景/皇居景',
        has_balcony: false,
        has_onsen: false,
        has_living_room: false,
        is_connectable: false,
        is_smoking: false,
        floor_info: '33-36层',
        highlights: ['高空俯瞰东京', '日式极简设计', '超大浴室'],
        suitable_for: ['商务', '情侣'],
        weekday_rate_min: 120000,
        weekday_rate_max: 140000,
        weekend_rate_min: 150000,
        weekend_rate_max: 180000,
        currency: 'JPY',
        rate_note: '含早餐',
        avg_advantage_percent: 12,
        advantage_level: 'fair',
        is_high_profit: false,
        hero_image_url: '',
        gallery_urls: [],
        floorplan_url: null,
        created_at: '2024-01-01',
        updated_at: '2024-01-01',
    },
    {
        room_id: 'aman-tokyo-suite',
        hotel_id: 'aman-tokyo',
        room_name_cn: '安缦套房',
        room_name_en: 'Aman Suite',
        room_name_local: 'アマンスイート',
        room_code_internal: 'AS',
        is_main_selling: false,
        is_entry_level: false,
        is_signature: true,
        recommendation_priority: 1,
        area_min_sqm: 157,
        area_max_sqm: 157,
        bed_type: '特大床',
        max_adults: 2,
        max_children: 2,
        max_occupancy: 4,
        view_type: '皇居+东京塔',
        has_balcony: false,
        has_onsen: true,
        has_living_room: true,
        is_connectable: false,
        is_smoking: false,
        floor_info: '37层',
        highlights: ['双面景观', '私人温泉浴', '专属管家', '安缦招牌体验'],
        suitable_for: ['UHNW', '蜜月', 'VIP'],
        weekday_rate_min: 350000,
        weekday_rate_max: 400000,
        weekend_rate_min: 450000,
        weekend_rate_max: 550000,
        currency: 'JPY',
        rate_note: '含早晚餐+管家',
        avg_advantage_percent: 15,
        advantage_level: 'good',
        is_high_profit: true,
        hero_image_url: '',
        gallery_urls: [],
        floorplan_url: null,
        created_at: '2024-01-01',
        updated_at: '2024-01-01',
    },

    // ===== 四季京都 =====
    {
        room_id: 'four-seasons-kyoto-deluxe',
        hotel_id: 'four-seasons-kyoto',
        room_name_cn: '豪华花园房',
        room_name_en: 'Deluxe Garden Room',
        room_name_local: 'デラックスガーデン',
        room_code_internal: 'DG',
        is_main_selling: true,
        is_entry_level: true,
        is_signature: false,
        recommendation_priority: 3,
        area_min_sqm: 50,
        area_max_sqm: 55,
        bed_type: '双人床',
        max_adults: 2,
        max_children: 1,
        max_occupancy: 3,
        view_type: '庭院景',
        has_balcony: true,
        has_onsen: false,
        has_living_room: false,
        is_connectable: false,
        is_smoking: false,
        floor_info: '1-2层',
        highlights: ['800年积翠园景观', '日式现代融合', '四季服务'],
        suitable_for: ['情侣', '商务'],
        weekday_rate_min: 95000,
        weekday_rate_max: 110000,
        weekend_rate_min: 120000,
        weekend_rate_max: 145000,
        currency: 'JPY',
        rate_note: '含早餐',
        avg_advantage_percent: 14,
        advantage_level: 'fair',
        is_high_profit: false,
        hero_image_url: '',
        gallery_urls: [],
        floorplan_url: null,
        created_at: '2024-01-01',
        updated_at: '2024-01-01',
    },
    {
        room_id: 'four-seasons-kyoto-townhouse',
        hotel_id: 'four-seasons-kyoto',
        room_name_cn: '町屋套房',
        room_name_en: 'Townhouse Suite',
        room_name_local: '町家スイート',
        room_code_internal: 'TH',
        is_main_selling: false,
        is_entry_level: false,
        is_signature: true,
        recommendation_priority: 1,
        area_min_sqm: 175,
        area_max_sqm: 175,
        bed_type: '特大床',
        max_adults: 2,
        max_children: 2,
        max_occupancy: 4,
        view_type: '积翠园全景',
        has_balcony: true,
        has_onsen: true,
        has_living_room: true,
        is_connectable: false,
        is_smoking: false,
        floor_info: '独栋',
        highlights: ['独立町屋建筑', '私人庭院', '温泉浴室', '管家服务'],
        suitable_for: ['蜜月', 'VIP', '特殊纪念日'],
        weekday_rate_min: 280000,
        weekday_rate_max: 320000,
        weekend_rate_min: 350000,
        weekend_rate_max: 420000,
        currency: 'JPY',
        rate_note: '含早晚餐+管家',
        avg_advantage_percent: 16,
        advantage_level: 'good',
        is_high_profit: true,
        hero_image_url: '',
        gallery_urls: [],
        floorplan_url: null,
        created_at: '2024-01-01',
        updated_at: '2024-01-01',
    },
];

// Helper functions
export function getRoomTypesByHotel(hotelId: string): RoomType[] {
    return roomTypes.filter(r => r.hotel_id === hotelId).sort((a, b) => a.recommendation_priority - b.recommendation_priority);
}

export function getRoomTypeById(roomId: string): RoomType | undefined {
    return roomTypes.find(r => r.room_id === roomId);
}

export function getMainSellingRooms(hotelId: string): RoomType[] {
    return roomTypes.filter(r => r.hotel_id === hotelId && r.is_main_selling);
}

export function getSignatureRoom(hotelId: string): RoomType | undefined {
    return roomTypes.find(r => r.hotel_id === hotelId && r.is_signature);
}
